### ISSUE TITLE
Can send with chatwoot but can receive message

### ISSUE THREAD

**Issue by KatiaSishost** [clairton/unoapi-cloud#17]
Hello, I installed everything as described but I have the following problem:

chatwoot:
my .env
WHATSAPP_CLOUD_BASE_URL=http://localhost:9876

my unoapi .env:
WEBHOOK_URL=http://localhost:3000/webhook/whatsapp
WEBHOOK_TOKEN=1yhQgCLJnniBveZSxAhbNig
WEBHOOK_HEADER=api_access_token

I can send messages but I can't receive them in chatwoot

unoapi console:
hostname":"chatwoot","msg":"Error on send to url /54911xxxxxxx with header

**Comment by clairton** [comment]
Try put in .env

WEBOOK_URL=http://localhost:3000/webhook/whatsapp

**Comment by KatiaSishost** [comment]
If I had that too... I don't know what happened but in the end it solved itself...

What I can't do is connect another account with another WhatsApp... should I set up 1 unoapi server for each account? (Saas)

**Comment by clairton** [comment]
You can Connect many WhatsApp account in a unoapi server

**Comment by KatiaSishost** [comment]
Well everything works correctly, what I can't do is connect... 2 accounts (not 2 users) 2 different accounts (SaaS) to the same oneapi

add a Platform Apps... and used that API in the unoapi .env configuration....

everything works fine on account 1... but on account 2... it doesn't work, when trying to send the first message it says could not be sent.

**Comment by clairton** [comment]
Hi, it is possible with web and worker when use redis and rabbitmq, but it's not documented yet

**Comment by clairton** [comment]
up redis and rabbitmq

put AMQP_URL and REDIS_URL in unoapi .env, after run:

`yarn cloud` up a single server and save message in redis and message broker rabbitmq

or

`yarn web` e `yarn worker` up a web and worker with redis and rabbitmq

in redis put a JSON value with key `unoapi-config:XXX`(XXX is the whatsapp number without the '+' character), the content  is a session config like so:


```json
{
   "authToken":"123",
   "rejectCalls":"Olá, ainda não consigo atender ligações no Whatsapp",
   "rejectCallsWebhook":"Estava te ligando no whatsapp",
   "webhooks":[
      {
         "url":"http://localhost:3000/webhooks/whatsapp",
         "header":"api_access_token",
         "token":"123456"
      }
   ]
}
```

The config option is the same .env vars with camelCase pattern

**Comment by KatiaSishost** [comment]
`WEBHOOK_URL=http://localhost:3000/webhooks/whatsapp
WEBHOOK_TOKEN=Cz27QHJ4gDYCGXt1JxHcbSuN
WEBHOOK_HEADER=api_access_token
IGNORE_GROUP_MESSAGES=true
IGNORE_BROADCAST_STATUSES=true

STORAGE_BUCKET_NAME=unoapi
STORAGE_ACCESS_KEY_ID=aEBeGHj1tpygXMfmcuof
STORAGE_SECRET_ACCESS_KEY=utQVnJOPERiZoYP6AJnDJqhUBaYRFMdfAl4FWYM6
STORAGE_REGION=us-east-1
STORAGE_ENDPOINT=http://localhost:9000
STORAGE_FORCE_PATH_STYLE=true

MINIO_SITE_REGION=$STORAGE_REGION
MINIO_ROOT_USER=$STORAGE_ACCESS_KEY_ID
MINIO_ROOT_PASSWORD=$STORAGE_SECRET_ACCESS_KEY
UNOAPI_AUTH_TOKEN=Cz27QHJ4gDYCGXt1JxHcbSuN

REJECT_CALLS=Oi, não consigo atender ligações no whatsapp, poderia me mandar uma mensagem?
REJECT_CALLS_WEBHOOK=Eu estava te ligando no whatsapp...
SEND_CONNECTION_STATUS=true

AMQP_URL=amqp://localhost:5672
REDIS_URL=redis://localhost:6379`

yarn && yarn build && yarn web
yarn run v1.22.19
$ node dist/web.js

in other console yarn worker... (show QR)

Now in chatwoot .env

`WHATSAPP_CLOUD_BASE_URL=http://localhost:9876/`

in redis:

`
const Redis = require('ioredis');

const redisUrl = 'redis://localhost:6379';

const whatsappNumber = '549xxxxx';

const sessionConfig = {
  authToken: '123', 
  rejectCalls: 'Olá, ainda não consigo atender ligações no Whatsapp',
  rejectCallsWebhook: 'Estava te ligando no whatsapp',
  webhooks: [
    {
      url: 'http://localhost:3000/webhooks/whatsapp',
      header: 'api_access_token',
      token: '123456',
    },
  ],
};

const redis = new Redis(redisUrl);

const redisKey = `unoapi-config:${whatsappNumber}`;

const redisValue = JSON.stringify(sessionConfig);

redis.set(redisKey, redisValue)
  .then(() => {
    console.log(`Configuración de sesión guardada en Redis con clave: ${redisKey}`);
  })
  .catch((error) => {
    console.error('Error al guardar la configuración en Redis:', error);
  })
  .finally(() => {
    // Cerrar la conexión a Redis
    redis.quit();
  });
`


the authToken and token: '123456', ? it's default? or need change someone?

When i try to add channel: We were not able to save the WhatsApp channel

**Comment by clairton** [comment]
The value in script must be this
`sessionConfig. webhooks[0].token = Cz27QHJ4gDYCGXt1JxHcbSuN`

In chatwoot to create inbox, at token put the value content of `authToken`, is 123

**Comment by KatiaSishost** [comment]
Well i try reinstalling all some times...

Ok, everything works perfectly on account 1... but on the 2nd account I run the script to configure the number of the 2nd account, I tried

const whatsappNumber = '549xxx1';

const sessionConfig = {
   authToken: '123',
   rejectCalls: 'Olá, I still can't attend links on Whatsapp',
   rejectCallsWebhook: 'I was linking you on WhatsApp',
   webhooks: [
     {
       url: 'http://localhost:3000/webhooks/whatsapp',
       header: 'api_access_token',
       token: '123456',
     },
   ],
};

and for the second:

const whatsappNumber = '549xxx2';

const sessionConfig = {
   authToken: '124',
   rejectCalls: 'Olá, I still can't attend links on Whatsapp',
   rejectCallsWebhook: 'I was linking you on WhatsApp',
   webhooks: [
     {
       url: 'http://localhost:3000/webhooks/whatsapp',
       header: 'api_access_token',
       token: '123456',
     },
   ],
};

both are successfully added to redis.

When I add the new Inboxes in the 2nd account... I place the data as I have placed it with the first account (changing the phone number clearly and the corresponding authToken)

It lets me add it, the QR is shown in the worker... the data is created in the mini and everything is perfect... but... when I add the contact and try to send the first message to scan the QR code... it says the message cannot be sent.

**Comment by clairton** [comment]
```js

const whatsappNumber = '549xxx1';

const sessionConfig = {
authToken: '123', // this token put in chatwoot when create/update inbox, this is used for chatwoot send authenticated requests to unoapi
rejectCalls: 'Olá, I still can't attend links on Whatsapp',
rejectCallsWebhook: 'I was linking you on WhatsApp',
webhooks: [
  {
    url: 'http://localhost:3000/webhooks/whatsapp',
    header: 'api_access_token',
    token: 'Cz27QHJ4gDYCGXt1JxHcbSuN', // put de current chatwoot token, this is for unoapi send authenticated requests to chatwoot
  },
],
};
```
in chatwoot some with this....

<img width="676" alt="Captura de Tela 2023-11-11 às 23 24 49" src="https://github.com/clairton/unoapi-cloud/assets/471685/90258a57-97f8-445f-9276-405e1037b6a3">

the second

```js
const whatsappNumber = '549xxx2';

const sessionConfig = {
authToken: '124',
rejectCalls: 'Olá, I still can't attend links on Whatsapp',
rejectCallsWebhook: 'I was linking you on WhatsApp',
webhooks: [
  {
    url: 'http://localhost:3000/webhooks/whatsapp',
    header: 'api_access_token',
    token: 'Cz27QHJ4gDYCGXt1JxHcbSuN',
  },
],
};
```

and chatwoot


<img width="584" alt="Captura de Tela 2023-11-11 às 23 25 19" src="https://github.com/clairton/unoapi-cloud/assets/471685/007af396-f8fb-48b5-aea3-c0009649c902">

Please, ignore chatwoot form errors for invalid values =)

**Comment by KatiaSishost** [comment]
![Platform](https://github.com/clairton/unoapi-cloud/assets/28807392/8dcfd857-cc17-4d03-ab3e-496d717988a0)

I'm totally confused, I did everything as is, in fact, as you told me, I've been doing it for 2 hours... are you sure this works with a 2nd ACCOUNT and not with a second USER? because I only have the problem with the 2nd account... I can add the inbox without problem therefore it is being validated... but the problem is sending the first message with the 2nd account.

**Comment by clairton** [comment]
You could help with docs after this please =)


Now there, send a vídeo or print of the error.
