### ISSUE TITLE
Is there any why to add the participants to the whatsapp group?

### ISSUE THREAD

**Issue by dhwaj1902** [clairton/unoapi-cloud#20]
Has Meta provided an API to add the participants to the WhatsApp group?

**Comment by clairton** [comment]
WhatsApp cloud api not work with grupos

Em dom., 19 de nov. de 2023 às 20:46, Dhwaj Gupta ***@***.***>
escreveu:

**Comment by dhwaj1902** [comment]
Hi, @clairton can you please suggest to me some way to add the participant to the group?

**Comment by clairton** [comment]
Uno is a Uno"fficial" whatsapp cloud api, this feature will be implemented with https://github.com/WhiskeySockets/Baileys, but not in scope for unoapi now
