### ISSUE TITLE
Mensagens de histórico sincronizadas fora de ordem

### ISSUE THREAD

**Issue by archanjoco** [clairton/unoapi-cloud#32]
Estou com um problema quando ativo a função de importar o histórico de mensagens na unoapi.

Ele sincroniza, mas todas as mensagens ficam com o horário da sincronia e não do horário real de recebimento da mensagem.

Exemplo... Uma mensagem de Outubro de 2023, quando sincronizada agora em 2024, fica com a data e a hora da sincronia.

Ou seja, ele importa até mesmo o histórico de trás pra frente e o histórico fica inutilizável.

**Comment by clairton** [comment]
Olá
Creio que agora está resolvido
