### ISSUE TITLE
Disconnected Number, Please Read QRCODE

### ISSUE THREAD

**Issue by marcelohhirata** [clairton/unoapi-cloud#34]
Estou com o chatwoot ( v.3.3.0) e Unoapi(latest) , durante algumas horas de uso, o número para de receber/enviar mensagens e é informado isso: Disconnected Number, Please Read QRCODE. Alguem sabe o que pode ser?

**Comment by clairton** [comment]
Ola tenta usar a 1.15.37-dev, esta em periodo de testes ainda, mas creio que deva resolver

**Comment by marcelohhirata** [comment]
mesmo jeito, caindo da mesma forma.

**Comment by clairton** [comment]
tenta a 1.15.38-dev

**Comment by caitano28** [comment]
to com o mesmo problema, testei a versão 1.15.45 e a dev mais recente mesma coisa alguma ideia ja até comentei na comunidade do zap.

![image](https://github.com/clairton/unoapi-cloud/assets/31899397/00f62ead-d1aa-42c4-beb3-ef5c8a2af6d3)

**Comment by caitano28** [comment]
Olhando o log do redis encontrei um alerta reclamando sobre isso e dando uma possível solução  
para editar o arquivo a seguir acrecentando essa ultima linha
nano /etc/sysctl.conf
![image](https://github.com/clairton/unoapi-cloud/assets/31899397/d619b20f-c03a-48f9-9e24-39ce5d9badcf)
vm.overcommit_memory = 1

reiniciar a vps (reboot)
 fazer esse comando no terminal
 sysctl vm.overcommit_memory=1

olhando no log do redis o erro sumiu, pelo que percebi esse erro do token vem quando a api crasha e reinicia eu acredito que deu alguma perca de dados no redis e vem o erro de token... não entendo bem a arquitetura mais vou seguir monitorando pelo dia para ver se resolveu esse erro!

Obs: uso vps hostinger KVM 2 com um numero em teste para por em produção.

**Comment by caitano28** [comment]
não resolveu

**Comment by clairton** [comment]
no container do redis precisa ter o volume configurado corretamente, se não é claro que perde os dado os dados quando reinicia.
mas não é a questão que a unoapi esta com problema.

**Comment by caitano28** [comment]
aqui resolveu alterando a liinha command no container do redis deixando assim command: redis-server --requirepass ${REDIS_PASSWORD} era oara ter reportado antes + tem mais de 10 dias sem problemas por mim pode fechar a issue
