### ISSUE TITLE
Envio de contato

### ISSUE THREAD

**Issue by edcarlosm** [clairton/unoapi-cloud#4]
As vezes ao enviar contato não vai ou vai com uma codificação estranha. exemplo.
0800 Dtel

[["tel", {"group"=>"item1", "waid"=>"558000012008"}, "text", "+55 800 001 2008"], ["tel", {"group"=>"item2"}, "text", "+55 800 001 9200"]]

**Comment by clairton** [comment]
creio que o problema ja foi solucionado, mas pode reabrir a conversa se ainda persistir
