### ISSUE TITLE
Mensagens digitadas no Whastapp Web ou no Whatsapp do celular não aparece no chatwoot

### ISSUE THREAD

**Issue by idealprint** [clairton/unoapi-cloud#43]
As mensagens digitadas no Whastapp Web ou no Whatsapp do celular não aparece no chatwoot:

No whatsapp web:
![image](https://github.com/clairton/unoapi-cloud/assets/56776316/8b6a6ab5-b753-4296-8666-51ddef43b858)

No chatwoot:
![image](https://github.com/clairton/unoapi-cloud/assets/56776316/f11ad93a-f376-4095-a6b7-4bc037361bd9)

**Comment by clairton** [comment]
olá
Aparecem sim
IGNORE_OWN_MESSAGES
IGNORE_YOURSELF_MESSAGES
Coloca essas duas como false, reinicia o servico, verifica se esta com a
ultima versao estavel, se esta usando redis, vai ter que alterar no redis.
Atenciosamente
*Clairton Rodrigo Heinzen*
*http://clairton.eti.br <http://clairton.eti.br/>*


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
03/04/24,
07:39:28

Em ter., 2 de abr. de 2024 às 20:48, idealprint ***@***.***>
escreveu:

**Comment by idealprint** [comment]
Fala Clairton!

Coloquei essas variaveis como false no chatwoot, na unoapi e no redis, e mesmo assim não consigo visualizar as próprias mensagens enviadas no celular ou whatsapp web.

Na Uno Api:
![image](https://github.com/clairton/unoapi-cloud/assets/56776316/11910c91-164d-4651-b876-de447d8ffa43)

No chatwoot (em duas partes)
![image](https://github.com/clairton/unoapi-cloud/assets/56776316/79e822b7-514e-4e3e-b66c-1184f360a733)
![image](https://github.com/clairton/unoapi-cloud/assets/56776316/ff6cbe57-ddbe-4cc0-ba66-6da62a2b3f73)

No Redis:
![image](https://github.com/clairton/unoapi-cloud/assets/56776316/39ff4cd2-251f-4be1-a608-df0fc52e51f0)

**Comment by clairton** [comment]
Tenta salvar as configurações pelo Chatwoot ver se funciona.
