### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by MNCamargo** [clairton/unoapi-cloud#45]
Eu baixo o docker-compose.yml o .env... faço as alterações nos meus domínios...

docker compor -d

até 10 recipientes...
1 saiu do chatwoot-migrate-1
1 saiu (1) unochat-minio-mc

mc: <ERRO> Não é possível inicializar o novo alias a partir das credenciais fornecidas. Obtenha "https://minio.mydomain.com.ar/probe-bsign-unoq9klnmruhx3awcnwkoi5upzurm4/?location=": tls: falha ao verificar o certificado: x509: o certificado é válido para aaec9267d31b876c8353053c3a3ba306.a02941ea8fe6b1a699f813bdb860 21 99.traefik.default, não minio. meudomínio .com.ar.
mc: <ERRO> Não foi possível criar o bucket `local/unochat`. Coloque "http://localhost:9000/unochat/": disque tcp 127.0.0.1:9000: connect: conexão recusada

Eu habilito a porta 9001

mínimo:
     imagem: quay.io/minio/minio:latest
     comando: servidor /dados --address ":9000" --console-address ":9001"
     volumes:
       -minio:/dados
     reiniciar: sempre
     arquivo_env: .env
     rótulos:
       - tragafik.enable=true
       - tragafik.http.services.minio.loadbalancer.server.port=9000
       - tragafik.http.routers.minio.rule=Host(`${MINIO_DOMAIN}`)
       - tragafik.http.routers.minio.entrypoints=http,https
       - tragafik.http.routers.minio.service=minio
       - tragafik.http.routers.minio.tls.certresolver=myresolver
     portos:
       -9001:9001

Posso entrar agora com localhost:9001 mas quando entro em minio.mydomain.com ele tenta carregar https://minio.mydomain.com:9001
e dê ERR_SSL_PROTOCOL_ERROR

Por outro lado, no chatwoot... quando cadastro a nova caixa de entrada, adiciono a nuvem https://unoapi.mydomain.com save... crio o contato, e ao enviar a mensagem diz "Não foi possível enviar , tente novamente":

my env:

# ------------------ atualizar esses obrigatoriamente inicio ---------------------#
CHATWOOT_DOMAIN=chat.mydomain.com.ar
MINIO_DOMAIN=minio.mydomain.com.ar
UNOAPI_DOMAIN=unoapi.mydomain.com.ar
LETSECRYPT_EMAIL=info@mydomain.com.ar
STORAGE_SECRET_ACCESS_KEY=unochat_password
UNOAPI_AUTH_TOKEN=any

# esse vai conseguir atualizar somente depois de criar o usuario
WEBHOOK_TOKEN=EFpiszP6n4wVR2RnYzE1Peb7 # i add the new token
# ------------------ atualizar esses obrigatoriamente final ---------------------#

HTTP_PROTOCOL=https

# url
CHATWOOT_URL=$HTTP_PROTOCOL://$CHATWOOT_DOMAIN
MINIO_URL=$HTTP_PROTOCOL://$MINIO_DOMAIN

# minio
ACTIVE_STORAGE_SERVICE=s3_compatible
STORAGE_ACCESS_KEY_ID=unochat_key
STORAGE_BUCKET_NAME=unochat
STORAGE_ENDPOINT=$MINIO_URL
STORAGE_FORCE_PATH_STYLE=true
STORAGE_REGION=us-east-1
MINIO_ROOT_USER=$STORAGE_ACCESS_KEY_ID
MINIO_ROOT_PASSWORD=$STORAGE_SECRET_ACCESS_KEY
MINIO_SERVER_URL=$MINIO_URL

#postgres
POSTGRES_PASSWORD=mudar_esse_valor
POSTGRES_USER=chatwoot_user
POSTGRES_DB=chatwoot_db

#rabbitmq
RABBITMQ_DEFAULT_USER=rabbitmq-uno-user
RABBITMQ_DEFAULT_PASS=rabbitmq-uno-password

# chatwoot
FRONTEND_URL=$CHATWOOT_URL
SECRET_KEY_BASE=0s8f9qwo89r923hr8y8yiUiugieigroey8ryqh3r98gqfhig9Tgfefwiryworywoi
DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB
REDIS_URL=redis://redis:6379
INSTALLATION_ENV=docker
NODE_ENV=production
RAILS_ENV=production

#unoapi
WEBHOOK_HEADER=api_access_token
WEBHOOK_URL=$CHATWOOT_URL/webhooks/whatsapp
AMQP_URL=amqp://$RABBITMQ_DEFAULT_USER:$RABBITMQ_DEFAULT_PASS@rabbitmq:5672
BASE_URL=$HTTP_PROTOCOL://$UNOAPI_DOMAIN
LOG_LEVEL=debug
UNO_LOG_LEVEL=debug

# compose project name
COMPOSE_PROJECT_NAME=unochat

**Comment by clairton** [comment]
O Chatwoot migrate vai rodar as migrations toda vez que inicia e parar depois, minio-mc cria o bucket se ainda não existe e depois para o serviço também 


O letsenceypt vai tentar gerar o ssl, olha os logs do traefik, você tem 3 tentativas em uma hora, depois ele bloqueia

**Comment by clairton** [comment]
Sobre os erros ao criar caixa de entrada, usa o token no Chatwoot o mesmo que vc tem na env UNOAPI_AUTH_TOKEN

**Comment by mario-evangelista-silva** [comment]
Bom dia! Estou iniciando estudos sobre sistemas omnichannel e estou muito interessado em aprender e utilizar estes sistemas.
Vendo alguns vídeos sobre o tema, todos estão utilizando o **traefik** como proxy gerador de certificados letsencrypt e isto torna os arquivos docker-compose maiores e precisa de algumas edições no docker-compose.
Acho que poderia ser utilizado o "Nginx Proxy Manager" que também é opensource e facilitaria em muito o trabalho.
Já testaram com o "Nginx Proxy Manager"?

**Comment by clairton** [comment]
Olá
É possível sim
Aí seria só remover a parte do traefik e usar ngnix ou qualquer outro similar

**Comment by clairton** [comment]
Leve em consideração que o localhost do container é diferente do localhost da maquina
