### ISSUE TITLE
Mensagens de Contatos novos não aparecem no Chatwoot quando a integração é com o Whatsapp Oficial

### ISSUE THREAD

**Issue by ailsoncgt** [clairton/unoapi-cloud#47]
Olá.
Estou usando o unoapi-cloud junto com a [versão alterada do chatwoot](https://github.com/clairton/chatwoot). A princípio tudo funciona como esperado excepto **o recebimento das mensagens de novos contatos dentro do chatwoot no canal de whatsapp oficial**.
O cenário é o seguinte: 

- Criei 2 caixas de entradas: A primeira com o whatsap oficial e a outra com o unoapi, porém o canal do whatsapp oficial dentro do chatwoot não recebe mensagens de contatos que não estajam cadastrados na agenda previamente. Para funcionar, tive que criar o contato antes e depois enviar a mensagem novamente para o canal.
O estranho é que a caixa de entrada com o unoapi recebe mensagens de contatos novos e consigo viaulizá-los dentro do chatwoot, mas não é o caso para o whatsapp oficial.

Ah, queria destacar aqui o excelente trabalho que você vme desenvolvendo no uno API. 👏🏾

**Comment by clairton** [comment]
Olá
obrigado!
Teria que olhar os logs para ver se acontece algum erro, ou talvez, se a conversa esta como pendente no chatwoot caso você tenha um bot conectado no chatwoot, pois fiz um teste aqui e deu certo a principio

**Comment by ailsoncgt** [comment]
Opa.
Acabei esquecendo de enviar o erro: 
Consegui ver esse erro aqui pelo sidekiq: `ActiveRecord::RecordInvalid: Validation failed: Phone number deve estar no formato e164`

**Comment by ailsoncgt** [comment]
@clairton , Boa tarde meu amigo.
Ainda continuo com o mesmo problema e o log é exatamente o que mandei na mensagem acima. Você teria disponibilidade para ver isso comigo algum dia em algum horário ?
Pode ser até no final de semana se vc puder.

**Comment by clairton** [comment]
Versao com correcao https://github.com/clairton/chatwoot/releases/tag/v3.11.11-uno

**Comment by ailsoncgt** [comment]
Valeeu @clairton . Vou testar aqui.
Só uma dúvida: essa sua versão inclui  a versão original 3.4 onde eles alteraram a licença, correto? Que no caso não pode ser costomizada mesmo no self-hosted.

**Comment by clairton** [comment]
Acho que há um equivoco nessa interpretação
com exceção da pasta enterprise, o codigo fonte é liberado como MIT

**Comment by ailsoncgt** [comment]
Sério ? O que mudou depois essa polémica versão então @clairton ?

**Comment by clairton** [comment]
nem lembro, hehhehe
