### ISSUE TITLE
Conversas em Grupo não aparecem

### ISSUE THREAD

**Issue by endreostange** [clairton/unoapi-cloud#49]
Olá, realizei a instalação, tudo tem funcionado corretamente, no entanto mesmo colocando o IGNORE_GROUP_MESSAGES como false, as mensagens em grupo não aparecem.

Outra dúvida, é possível compartilhar contatos e criar campanhas no chatwoot?

**Comment by caitano28** [comment]
bom dia, depois que você loga a primeira vez no zap ele armazena as config no Redis então alterando apenas o .env não vai refletir no número já logado, tu pode alterar pelo redis (usando a interface gráfica redis comander) ou pela rota linkUnoApi/session/55DD9xxxxxxxx pela rota tem que por a chave de criptografia utilizada para sincronizar com api (enviada depois de ler o qrcode), depois de alterar reinicia o container da UNOAPI, pelo chatwoot não tem como (poderia fazer com uma rota no n8n enviando pro endpoint de message do unoapi, salva em um banco de dados o nome, numero e texto da campanha e chama a rota do n8n...)

**Comment by clairton** [comment]
Olá
Agora com as configurações no próprio Chatwoot fica mais fácil
Poderia testar?
Por enquanto vou estar fechando
