### ISSUE TITLE
Como conectar com o TypeBot?

### ISSUE THREAD

**Issue by idealprint** [clairton/unoapi-cloud#55]
Como fazer para conectar o typebot com a unoapi e o chatwoot?

**Comment by idealprint** [comment]
segui o exemploe em https://github.com/clairton/unoapi-cloud/blob/main/examples/typebot/README.md
mas não consegui. Consegue me dar um exemplo de como colocar essa parte:
  "webhooks":[
    {
      "urlAbsolute":"YOUR TYPEBOT URL"
      "token":"Bearer YOR TOKEN",
      "header":"Authorization"
    }
  ],
  
  pelo PORTAINER? Uso o redis. fiquei na dúvida se coloco como uma variável de ambiente, e como colocar.

**Comment by idealprint** [comment]
Essa palavra Bearer deve ficar na variável?

**Comment by clairton** [comment]
Não precisa obrigatoriamente usá-la pode enviar somente o token mesmo
