### ISSUE TITLE
Bug no envio de mensagens de áudio, imagem ou Doc. ( Mensagem em BRANCO)

### ISSUE THREAD

**Issue by BrunoFrost** [clairton/unoapi-cloud#6]
Olá a todos!
O problema é o seguinte:

Toda vez que é enviado uma mensagem de áudio, imagem, vídeo ou doc, é enviado uma mensagem em branco sem conteúdo algum e logo depois o arquivo é enviado. Isso não acontece quando o envio é somente texto.

Durante a instalação não houve nenhum erro. 
Atualmente minha VPS é a Hetzner, com 3 CPU e 4GB de ram. Instalei tudo no Ubuntu 22.04. 

Tal erro acontece tanto no Whatsatpp business, quanto no normal.

![image](https://user-images.githubusercontent.com/88799055/225298027-97f0daba-3498-46de-b61b-6bab3d010ec6.png)

![image](https://user-images.githubusercontent.com/88799055/225298852-929569ef-d5b8-4a1f-90d4-07015c9b0197.png)

**Comment by giquieu** [comment]
@BrunoFrost , @InfoDigitalEL 
O problem persiste?

**Comment by clairton** [comment]
without response
