### ISSUE TITLE
Show info that message is forwarded and viewOnce (Chatwoot)

### ISSUE THREAD

**Issue by laianeramos** [clairton/unoapi-cloud#80]
Is important to know when a contact sends a forwarded message, to avoid confusions in communication. The same applies for view once messages, it would be important to know when a contact sends a view once message so we can check the phone or answer the client informing that we can’t see his message.

![image](https://github.com/user-attachments/assets/dd561fec-52e0-480b-a3a6-2ce052f05ee5)

### Sugestões

1. Create a private message on conversation informing that the message is forwarded.

2. Show a warning just like when a message is edited (obs.: this is what happens with evolution api when a message is edited, with unoapi another message is sent)
![image](https://github.com/user-attachments/assets/a2956c9c-dca6-4594-993c-2eca4fc205fc)

3. For view once, a private note:
![image](https://github.com/user-attachments/assets/0dbd29b7-d506-4aae-863e-586076e1fbb9)

**Comment by clairton** [comment]
hi
thanks for issue
audios with view once use tag viewOnceMessageV2Extension and is add in version 1.18.2, together ptvMessage

edited message is not altered, because unoapi not known chatwoot, only send to webhook(chatwoot, typebot, n8n.....), Private messages belongs to chatwoot

**Comment by laianeramos** [comment]
@clairton fiz uns testes aqui e somente estão chegando as fotos e vídeos viewOnce, os áudios não chegam. 
Observei que as de image e video chegaram como viewOnceMessageV2 e as de audio como viewOnceMessageV2Extension, caso ajude em algo.

**Comment by laianeramos** [comment]
@clairton testei com outra pessoa e no dela chegou o áudio, no meu não 🥲 v1.18.2 + Chatwoot3.13.1-uno (o meu), e ela v1.18.2 + Chatwoot N 3.12.0

**Comment by clairton** [comment]
teria que olhar nos logs da unoapi, como é o formato da mensagem que chega no seu numero de whatsapp que não esta dando certo. estou com as mesmas versoes que para você não deu certo, mas que funcionou para mim. É alguma particularidade no seu payload da mensagem, creio eu.

**Comment by laianeramos** [comment]
eu salvei os logs, mas esqueci de mandar aqui rsrs 

[logs teste audio viewonce.txt](https://github.com/user-attachments/files/17175710/logs.teste.audio.viewonce.txt)
