### ISSUE TITLE
Error get from unoapi-cloud

### ISSUE THREAD

**Issue by nimaam** [clairton/unoapi-cloud#87]
“body”: “Unoapi version 1.20.0 message failed in queue unoapi.incoming\n\nstack trace: undefined\n\n\nerror: undefined\n\ndata: {\n "payload": {\n "to": "905446227675",\n "type": "text",\n "text": {\n "body": "Unoapi version 1.20.0 message failed in queue unoapi.incoming\n\nstack trace: undefined\n\n\nerror: undefined\n\ndata: {\n \"payload\": {\n \"to\": \"905446227675\",\n \"type\": \"text\",\n \"text\": {\n \"body\": \"Unoapi version 1.20.0 message failed in queue unoapi.baileys.listener\\n\\nstack trace: TypeError: Invalid URL\\n at new URL (node:internal/url:804:36)\\n at parseUrl (/home/u/app/node_modules/@smithy/url-parser/dist-cjs/index.js:29:21)\\n at toEndpointV1 (/home/u/app/node_modules/@smithy/middleware-endpoint/dist-cjs/index.js:112:41)\\n at customEndpointProvider (/home/u/app/node_modules/@smithy/middleware-endpoint/dist-cjs/index.js:232:65)\\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n\\n\\nerror: Invalid URL\\n\\ndata: {\\n \\\"messages\\\": [\\n {\\n \\\"key\\\": {\\n \\\"remoteJid\\\": \\\"905446227675@s.whatsapp.net\\\",\\n \\\"fromMe\\\": false,\\n \\\"id\\\": \\\"FFA7FF3532BCFDF0F764F04BDBBD1ADF\\\"\\n },\\n \\\"messageTimestamp\\\": 1729435368,\\n \\\"pushName\\\": \\\"احسان الله نظری💔💔\\\",\\n \\\"broadcast\\\": false,\\n \\\"message\\\": {\\n \\\"audioMessage\\\": {\\n \\\"url\\\": \\\"[https://mmg.whatsapp.net/v/t62.7117-24/11706794_1589307908602930_1685273643204951892_n.enc?ccb=11-4&oh=01_Q5AaID6dx7MZdOKmDMP4JOotipojtovDrVao95GqzQ05SAM8&oe=673C7434&_nc_sid=5e03e0&mms3=true\\\\\\\](https://mmg.whatsapp.net/v/t62.7117-24/11706794_1589307908602930_1685273643204951892_n.enc?ccb=11-4&oh=01_Q5AaID6dx7MZdOKmDMP4JOotipojtovDrVao95GqzQ05SAM8&oe=673C7434&_nc_sid=5e03e0&mms3=true%5C%5C%5C%5C%5C%5C%5C)”,\\n \\\"mimetype\\\": \\\"audio/ogg; codecs=opus\\\",\\n \\\"fileSha256\\\": \\\"zAtA4PsCzEuvyv10oWPOq92z0GnP99c15+OCknuoNaI=\\\",\\n \\\"fileLength\\\": \\\"28355\\\",\\n \\\"seconds\\\": 12,\\n \\\"ptt\\\": true,\\n \\\"mediaKey\\\": \\\"2ZdER7qQE+T3o61pf3EfJn7vQRhVtE7g9y4SXKjvR9A=\\\",\\n \\\"fileEncSha256\\\": \\\"PmjCQrCR6BQWeBV6GKl0fWrcWLHwVfvFpo+Shx2uuRI=\\\",\\n \\\"directPath\\\": \\\"/v/t62.7117-24/11706794_1589307908602930_1685273643204951892_n.enc?ccb=11-4&oh=01_Q5AaID6dx7MZdOKmDMP4JOotipojtovDrVao95GqzQ05SAM8&oe=673C7434&_nc_sid=5e03e0\\\",\\n \\\"mediaKeyTimestamp\\\": \\\"1729435357\\\",\\n \\\"waveform\\\": \\\"AAAAGw9jXUdXQitXVRogLmJSV1ZOIlpfI09AQgFBT0xXViZSYllRXFpQYk4pXFhQVlUBAA8SRE1VRldNRU8sAA==\\\"\\n },\\n \\\"messageContextInfo\\\": {\\n \\\"deviceListMetadata\\\": {\\n \\\"recipientKeyHash\\\": \\\"NdLYFa4HtvHqsQ==\\\",\\n \\\"recipientTimestamp\\\": \\\"1729344009\\\"\\n },\\n \\\"deviceListMetadataVersion\\\": 2\\n }\\n },\\n \\\"profilePicture\\\": \\\"[https://pps.whatsapp.net/v/t61.24694-24/420663914_2126384097698506_6205185054833131444_n.jpg?stp=dst-jpg_s96x96&ccb=11-4&oh=01_Q5AaILbbxtMr9RBarGZjmUdaeuFjs1_Yalgz2WvxMKb29kEf&oe=67222F99&_nc_sid=5e03e0&_nc_cat=109\\\\\\\](https://pps.whatsapp.net/v/t61.24694-24/420663914_2126384097698506_6205185054833131444_n.jpg?stp=dst-jpg_s96x96&ccb=11-4&oh=01_Q5AaILbbxtMr9RBarGZjmUdaeuFjs1_Yalgz2WvxMKb29kEf&oe=67222F99&_nc_sid=5e03e0&_nc_cat=109%5C%5C%5C%5C%5C%5C%5C)“\\n }\\n ],\\n \\\"type\\\": \\\"notify\\\",\\n \\\"splited\\\": true\\n}\"\n }\n },\n \"id\": \"d1e3bb40-8ef1-11ef-ad1d-7f0adc84cf6f\",\n \"options\": {\n \"priority\": 5\n }\n}"\n }\n },\n "id": "6cf3c6c0-8ef2-11ef-ad1d-7f0adc84cf6f",\n "options": {\n "priority": 5\n }\n}”

**Comment by clairton** [comment]
Olá
É uma URL que está vazia, provavelmente do webhook
